repo:
  github:
    owner: dereulenspiegel
    repo: firmware_craftbeerpi

manager:
  allowPrerelease: false
  checkInterval: 12h
unixSocket:
  enabled: true
  socketPath: /var/run/updatemanager.sock
