// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"
	 "github.com/dereulenspiegel/raucgithub/repository"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// Updates provides a mock function with given fields: ctx
func (_m *Repository) Updates(ctx context.Context) ([]repository.Update, error) {
	ret := _m.Called(ctx)

	var r0 []repository.Update
	if rf, ok := ret.Get(0).(func(context.Context) []repository.Update); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.Update)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_Updates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Updates'
type Repository_Updates_Call struct {
	*mock.Call
}

// Updates is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Repository_Expecter) Updates(ctx interface{}) *Repository_Updates_Call {
	return &Repository_Updates_Call{Call: _e.mock.On("Updates", ctx)}
}

func (_c *Repository_Updates_Call) Run(run func(ctx context.Context)) *Repository_Updates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Repository_Updates_Call) Return(_a0 []repository.Update, _a1 error) *Repository_Updates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
