name: Release
on: 
  push: 
    tags: ["v*"]

jobs:
  test-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: git fetch --force --tags
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: "1.19"
    - name: Install dependencies
      run: |
        go version
        go mod download
        pip install pydbus
    - name: Run vet & lint
      run: |
        go vet ./...
    - name: Install DBus policy
      run: sudo cp contrib/dbus-policy.conf /etc/dbus-1/system.d/com.github.dereulenspiegel.rauc.conf
    - name: Reload DBUs to take policy effect
      run: sudo systemctl restart dbus
    - name: Run testing
      run: go test --tags dbus_test -v ./...
    - uses: goreleaser/goreleaser-action@v4
      with:
        distribution: goreleaser
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
