name: Tests
on: 
  push: 
    branches: ["*"]
  pull_request: 
    branches: ["*"]

jobs:
  run-tests:
    strategy:
      matrix:
        go_version: ["1.19", "1.18"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: "${{ matrix.go_version }}"
    - name: Install dependencies
      run: |
        echo $USER
        pwd
        go version
        go mod download
        pip install pydbus
        pip install glib
        pip install requests_unixsocket
    - name: Run vet & lint
      run: |
        go vet ./...
    - name: Install DBus policy
      run: sudo cp contrib/dbus-policy.conf /etc/dbus-1/system.d/com.github.dereulenspiegel.rauc.conf
    - name: Reload DBUs to take policy effect
      run: sudo systemctl restart dbus
    - name: Run testing
      run: go test --tags dbus,dbus_test -v ./...
